# Generated by Django 5.2.7 on 2025-11-26 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplayer',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Sala 1', max_length=50),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='RoomPlayer',
        ),
    ]
