# Generated by Django 5.2.7 on 2025-12-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_room_created_at_room_host_alter_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='pattern',
            field=models.CharField(choices=[('linea_completa', 'Cartón lleno'), ('t', 'Forma T'), ('x', 'Forma X'), ('l', 'Forma L')], default='linea_completa', max_length=20),
        ),
    ]
